apiVersion: v1
kind: ConfigMap
metadata:
  name: chisel-exit-node-resources
  namespace: projectsveltos
data:
  exit-node.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: chisel-operator-system
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: racknerd-exit-node-auth
      namespace: chisel-operator-system
    type: Opaque
    stringData:
      auth: Mershab:Fahimm123
    ---
    apiVersion: chisel-operator.io/v1
    kind: ExitNode
    metadata:
      name: exit-node1
      namespace: chisel-operator-system
    spec:
      host: "66.63.162.121"
      port: 9090
      auth: racknerd-exit-node-auth
