apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: hub-certmanager
spec:
  clusterSelector:
    matchLabels:
      cluster-type: hub
  helmCharts:
    - repositoryURL: https://charts.jetstack.io
      chartName: cert-manager
      chartVersion: "1.19.x"
      releaseName: cert-manager
      releaseNamespace: cert-manager
      values: |
        installCRDs: true
        nodeSelector:
          node-role.kubernetes.io/agent: ""
  policyRefs:
    - name: hub-certmanager-resources
      namespace: projectsveltos
      kind: ConfigMap
