apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: hub-rancher
spec:
  clusterSelector:
    matchLabels:
      cluster-type: hub
  helmCharts:
    - repositoryURL: https://releases.rancher.com/server-charts/stable
      chartName: rancher
      chartVersion: "2.13.x"
      releaseName: rancher
      releaseNamespace: cattle-system
      values: |
        hostname: rancher.homelab.dev
        replicas: 1
        nodeSelector:
          topology.homelab.dev/chassis: supermicro

    - repositoryURL: https://rancher.github.io/turtles
      chartName: rancher-turtles
      chartVersion: "0.25.x"
      releaseName: rancher-turtles
      releaseNamespace: rancher-turtles-system
      values: |
        nodeSelector:
          node-role.kubernetes.io/agent: ""
