apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: workload-knative
spec:
  dependsOn:
    - workload-ingress
  clusterSelector:
    matchLabels:
      cluster-type: workload
  helmCharts:
    - repositoryURL: https://knative.github.io/operator
      chartName: knative-operator
      chartVersion: "1.x"
      releaseName: knative-operator
      releaseNamespace: knative-operator
  policyRefs:
    - name: knative-serving-resources
      namespace: projectsveltos
      kind: ConfigMap
      deploymentType: Remote
