apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: workload-ingress
spec:
  clusterSelector:
    matchLabels:
      cluster-type: workload
  helmCharts:
    - repositoryURL: https://traefik.github.io/charts
      chartName: traefik
      chartVersion: "39.x"
      releaseName: traefik
      releaseNamespace: traefik-system
      values: |
        service:
          spec:
            loadBalancerClass: chisel-operator.io/chisel-operator-class
        ingressRoute:
          dashboard:
            enabled: false
        api:
          dashboard: true
          insecure: true
        providers:
          kubernetesGateway:
            enabled: true
          knative:
            enabled: true
        experimental:
          knative: true

    - repositoryURL: https://chisel-operator.github.io/charts
      chartName: chisel-operator
      chartVersion: "0.x"
      releaseName: chisel-operator
      releaseNamespace: chisel-operator-system
      values: |
        loadBalancerClass: chisel-operator.io/chisel-operator-class
  policyRefs:
    - kind: ConfigMap
      name: chisel-exit-node-resources
      namespace: projectsveltos
      deploymentType: Remote
    - kind: ConfigMap
      name: traefik-dashboard-resources
      namespace: projectsveltos
      deploymentType: Remote
