apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-certmanager-resources
  namespace: projectsveltos
data:
  clusterissuer.yaml: |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: admin@mershab.com  # TODO: set actual email
        privateKeySecretRef:
          name: letsencrypt-prod-account-key
        solvers:
          - http01:
              gatewayHTTPRoute:
                parentRefs:
                  - name: workload-gateway
                    namespace: traefik-system
