apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: metal3
spec:
  version: v1.12.2
  deployment:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/agent: ""
