apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: workload-cp
  namespace: workload-cluster
spec:
  replicas: 1
  version: "v1.29.0"
  dataStoreName: default
#  networkProfile:
#    port: 6443
#    podCidr: "10.244.0.0/16"
#    serviceCidr: "10.96.0.0/12"
  addons:
    coreDNS: {}
    konnectivity: {}
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - InternalIP
  network:
    serviceAnnotations:
      metallb.universe.tf/address-pool: virt-ip-pool
    serviceType: LoadBalancer
